[language.elixir]
remote = "https://github.com/elixir-lang/tree-sitter-elixir"
revision = "a11a686303355a518b0a45dea7c77c5eebb5ec22"

[language.erlang]
remote = "https://github.com/the-mikedavis/tree-sitter-erlang"
revision = "47c6d15c2a25df09378af9c681d0892e5c893c39"
