name: "CI"
on: push

jobs:
  tests:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Authenticate with Cachix
      uses: cachix/cachix-action@v10
      with:
        name: tspm
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Build flake
      run: nix build

      # detects reproducibility failures
    - name: Re-build flake
      run: nix build --rebuild

      # runs tree-sitter tests as well
    - name: Check flake outputs
      run: nix flake check

    - name: Build artifacts
      if: github.ref == 'refs/heads/main'
      run: nix build .#artifacts

    - name: Publish artifacts to registry
      if: github.ref == 'refs/heads/main'
      uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: tspm
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT: https://nyc3.digitaloceanspaces.com
        AWS_REGION: nyc3
        SOURCE_DIR: ./result/
