name: CI
on: push

jobs:
  test:
    name: Check
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Authenticate with Cachix
      uses: cachix/cachix-action@v10
      with:
        name: tspm
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Build flake
      run: nix build

      # detects reproducibility failures
    - name: Re-build flake
      run: nix build --rebuild

      # runs tree-sitter tests as well
    - name: Check flake outputs
      run: nix flake check

    - name: Build artifacts
      if: github.ref == 'refs/heads/main'
      run: nix build .#artifacts

    - run: ls -al

    - name: Publish artifacts to registry
      if: github.ref == 'refs/heads/main'
      run: |
        nix profile install nixpkgs#aws

        # upstream: https://github.com/jakejarvis/s3-sync-action/blob/7ed8b112447abb09f1da74f3466e4194fc7a6311/entrypoint.sh
        aws configure --profile artifact-publish-profile <<-EOF > /dev/null 2>&1
        ${{ secrets.ACCESS_KEY_ID }}
        ${{ secrets.SECRET_ACCESS_KEY }}
        ${{ env.AWS_REGION }}
        text
        EOF

        aws s3 sync ./result s3://tspm/ \
          --profile artifact-publish-profile \
          --endpoint-url https://nyc3.digitaloceanspaces.com \
          --acl public-read --follow-symlinks --no-progress

        aws configure --profile artifact-publish-profile <<-EOF > /dev/null 2>&1
        null
        null
        null
        text
        EOF
