name: "CI"
on: push

jobs:
  tests:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Check flake
      run: nix flake check
