name: "CI"
on: push

jobs:
  tests:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Authenticate with Cachix
      uses: cachix/cachix-action@v10
      with:
        name: tspm
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Build flake
      run: nix build

      # detects reproducibility failures
    - name: Re-build flake
      run: nix build --rebuild
